version: '3.8'

services:
  starter-kit:
    container_name: starter-kit
    build: .
    ports:
      - "8000:8000"
    environment:
      - NAME=Python-starter-kit
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    networks:
      - my-custom-network
networks:
  my-custom-network:
    external: true